# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' perform a compound transformation on a vector, including clipping
#'
#' @param x numeric vector
#' @param inner numeric constant
#' @param outer numeric constan
#'
#' @return numeric vector of same length as x, containing outer*clip4(inner*x)
#' 
clip4 <- function(x, inner, outer) {
    .Call('_umap_clip4', PACKAGE = 'umap', x, inner, outer)
}

#' compute Euclidean distance between two vectors
#'
#' @param x numeric vector
#' @param y numeric vector
#'
#' @return euclidean norm of x-y
#'
dEuclidean <- function(x, y) {
    .Call('_umap_dEuclidean', PACKAGE = 'umap', x, y)
}

